import { ColumnHeader } from "../Components/CommonComponents/Table/TableDataTypes";

export const analyticsTableColumnHeaders: ColumnHeader[] = [
    {
      id: 1,
      isAdded: true,
      name: "Date",
      dataField: "date",
      filterType: "date",
      textAlign: "flex-start",
      toggle: false,
    },
    {
      id: 2,
      isAdded: true,
      name: "App",
      dataField: "appName",
      filterType: "name",
      textAlign: "flex-start",
      toggle: false,
    },
    {
      id: 3,
      isAdded: true,
      name: "Clicks",
      dataField: "clicks",
      filterType: "range",
      textAlign: "flex-start",
      toggle: true,
    },
    {
      id: 4,
      isAdded: true,
      name: "Requests",
      dataField: "requests",
      filterType: "range",
      textAlign: "flex-start",
      toggle: true,
    },
    {
      id: 5,
      isAdded: true,
      name: "Ad Response",
      dataField: "responses",
      filterType: "range",
      textAlign: "flex-start",
      toggle: true,
    },
    {
      id: 6,
      isAdded: true,
      name: "Impression",
      dataField: "impressions",
      filterType: "range",
      textAlign: "flex-start",
      toggle: true,
    },
    {
      id: 7,
      isAdded: true,
      name: "Revenue",
      dataField: "revenue",
      filterType: "range",
      textAlign: "flex-start",
      toggle: true,
    },
    {
      id: 8,
      isAdded: true,
      name: "Fill rate",
      dataField: "fillRate",
      filterType: "range",
      textAlign: "flex-start",
      toggle: true,
    },
    {
      id: 9,
      isAdded: true,
      name: "CTR",
      dataField: "ctr",
      filterType: "range",
      textAlign: "flex-start",
      toggle: true,
    },
  ];